image: Visual Studio 2017
platform: x64
configuration: Release

environment:
    matrix:
        - DFLAG: "-DUSESSE -DUSEOMP"

        - DFLAG: "-DUSEAVX -DUSEOMP"

        - DFLAG: "-DUSEOMP"

        - DFLAG: ""

install: 
    - cmd: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat

build:
    - cmd: nmake -f Makefile.win all

test_script:
    - cd demo && demo.bat
