language: cpp

matrix:
    include:
        - os: linux
        - os: osx

install:
    - make -e

env:
    - DFLAG="-DUSESSE -DUSEOMP"
    - DFLAG="-DUSEAVX -DUSEOMP"
    - DFLAG="-DUSEOMP"
    - DFLAG=""

script:
    - cd demo && sh demo.sh
